weights: /workdir/generation/ntu-xsub/hinge_loss_w_100_sgd/epoch40_generator.pt
work_dir: /workdir/generation/ntu-xsub/hinge_loss_w_100_sgd

# feeder
feeder: feeder.feeder_generation.Feeder
test_feeder_args:
  data_path: /data/NTU-RGB-D/xsub/val_data.npy
  label_path: /data/NTU-RGB-D/xsub/val_label.pkl
  mask_size: 5
  window_size: 64
  num_data: 100
  debug: False

# model
generator: net.graph_gen.Generator
gen_args:
  in_channels: 3
  num_class: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

discriminator: net.graph_gen.Discriminator
dis_args:
  in_channels: 3
  num_class: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test
# original batch_size = 256
phase: test
device: [0,1,2,3]
test_batch_size: 4



