weights: ./work_dir/recognition/kinetics_skeleton/ST_GCN/epoch40_generator.pt
work_dir: ./work_dir/recognition/kinetics_skeleton/ST_GCN

# feeder
feeder: feeder.feeder_generation.Feeder
test_feeder_args:
  data_path: /home/wuqiang/Workspace/2_generative_model/3_DA_Gesture/2_ST_GCN/st-gcn-master/data/NTU-RGB-D/xsub/val_data.npy
  label_path: /home/wuqiang/Workspace/2_generative_model/3_DA_Gesture/2_ST_GCN/st-gcn-master/data/NTU-RGB-D/xsub/val_label.pkl
  mask_size: 5
  window_size: 64
  num_data: 100
  debug: False

# model
generator: net.graph_gen.Generator
gen_args:
  in_channels: 3
  num_class: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

discriminator: net.graph_gen.Discriminator
dis_args:
  in_channels: 3
  num_class: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test
# original batch_size = 256
phase: test
device: [0]
test_batch_size: 1



